package ui.user;

import model.User;
import model.surat.SuratPengantar;
import model.surat.SuratPengantarDomisili;
import model.surat.SuratPengantarKK;
import model.surat.SuratPengantarKTP;
import model.surat.SuratPengantarKelahiran;
import model.surat.SuratPengantarKematian;
import model.surat.SuratPengantarMutasi;
import model.surat.SuratPengantarNikah;
import model.surat.SuratPengantarUsaha;
import database.Koneksi;
import database.SmartDatabase;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import ui.user.DashboardUser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ui.Login;

public class PengajuanSurat extends javax.swing.JFrame {

    private Connection conn;
    private PreparedStatement pst;
    private ResultSet rst;
    private SmartDatabase database;
    private SuratPengantar dataSurat;
    private User dataUser = new User();
    private final String status = "Masih diproses";
    private final String link = "-";

    /**
     * Creates new form PengajuanSurat
     */
    public PengajuanSurat(String input) {
        initComponents();
        dataUser.setPassword(input);
        try {
            //melakukan koneksi ke database
            database = new SmartDatabase();
            conn = Koneksi.koneksi();
            //menyiapkan statement & memeanggil method queryProfile()
            pst = conn.prepareStatement(database.queryProfile());
            pst.setString(1, input);
            rst = pst.executeQuery();//eksekusi query

            //pengondisian
            if (rst.next()) {
                //mengambil data sesuai nama kolomnya
                edtNama.setText(rst.getString("Nama"));
                edtNIK.setText(rst.getString("NIK"));
                edtAlamat.setText(rst.getString("alamat"));
                edtRT.setText(rst.getString("RT"));
                edtRW.setText(rst.getString("RW"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    //polymorhism
    public String[] getOptionSurat() {
        SuratPengantar[] sp = new SuratPengantar[8];
        sp[0] = new SuratPengantarDomisili();
        sp[1] = new SuratPengantarKK();
        sp[2] = new SuratPengantarKTP();
        sp[3] = new SuratPengantarKelahiran();
        sp[4] = new SuratPengantarKematian();
        sp[5] = new SuratPengantarMutasi();
        sp[6] = new SuratPengantarNikah();
        sp[7] = new SuratPengantarUsaha();

        String st[];
        String surat = "-,";
        for (int i = 0; i < sp.length; i++) {
            surat = surat + sp[i].tampilNamaSurat() + ",";
        }
        st = surat.split(",");
         
        return st;
    }

    public void insertDataDashboard() {
        dataSurat = new SuratPengantar(status, link);
        try {
            database = new SmartDatabase();
            conn = Koneksi.koneksi();
            pst = conn.prepareStatement(database.insertDashboard(dataSurat));
            pst.execute();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void insertJenisSurat() {
        //melakukan set data inputan dari combo box dan edit text
        dataSurat.setNamaSurat(cbSuratPengantar.getSelectedItem().toString().trim());
        

        try {
            database = new SmartDatabase();
            conn = Koneksi.koneksi(); 
            pst = conn.prepareStatement(database.insertJenisSurat(dataSurat.getNamaSurat()));
            pst.execute();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void insertSuratPengantar() {
        /*inisialisasi objek supaya format tanggal yang di inputkan 
        menjadi sesuai dengan format tanggal di sql*/
        java.sql.Date date = new Date(edtTanggal.getDate().getTime());
        //melakukan set data inputan dari edit text
        dataSurat.setTanggalSurat(date.toString());
        dataSurat.setKeperluan(edtKeperluan.getText().toString().trim());
        dataSurat.setNik(edtNIK.getText().toString().trim());

        dataSurat = new SuratPengantar(dataSurat.getTanggalSurat(), 
                    dataSurat.getKeperluan(), dataSurat.getNik());

        try {
            database = new SmartDatabase();
            conn = Koneksi.koneksi();
            pst = conn.prepareStatement(database.insertSuratPengantar(dataSurat));
            pst.execute();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnProfile = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cbSuratPengantar = new javax.swing.JComboBox<>();
        edtNama = new javax.swing.JTextField();
        edtNIK = new javax.swing.JTextField();
        edtAlamat = new javax.swing.JTextField();
        edtRT = new javax.swing.JTextField();
        edtRW = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtKeperluan = new javax.swing.JTextArea();
        edtTanggal = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        btnAjukan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\btnPengajuanSurat_blue.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        btnProfile.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\btnProfile_white.png")); // NOI18N
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileMouseClicked(evt);
            }
        });
        jPanel1.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        btnDashboard.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\btnDashboard.png")); // NOI18N
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        btnLogOut.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\log out.png")); // NOI18N
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\frame.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\icon close.png")); // NOI18N

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCloseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 40, -1));

        btnMinimize.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\icon minimize.png")); // NOI18N

        javax.swing.GroupLayout btnMinimizeLayout = new javax.swing.GroupLayout(btnMinimize);
        btnMinimize.setLayout(btnMinimizeLayout);
        btnMinimizeLayout.setHorizontalGroup(
            btnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMinimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );
        btnMinimizeLayout.setVerticalGroup(
            btnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMinimizeLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 40, -1));

        cbSuratPengantar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbSuratPengantar.setModel(new javax.swing.DefaultComboBoxModel<>(getOptionSurat()));
        jPanel2.add(cbSuratPengantar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 360, 50));

        edtNama.setEditable(false);
        edtNama.setBackground(new java.awt.Color(255, 255, 255));
        edtNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtNama.setBorder(null);
        edtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNamaActionPerformed(evt);
            }
        });
        jPanel2.add(edtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 890, 30));

        edtNIK.setEditable(false);
        edtNIK.setBackground(new java.awt.Color(255, 255, 255));
        edtNIK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtNIK.setBorder(null);
        jPanel2.add(edtNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 640, 30));

        edtAlamat.setEditable(false);
        edtAlamat.setBackground(new java.awt.Color(255, 255, 255));
        edtAlamat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtAlamat.setBorder(null);
        jPanel2.add(edtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 720, 40));

        edtRT.setEditable(false);
        edtRT.setBackground(new java.awt.Color(255, 255, 255));
        edtRT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtRT.setBorder(null);
        jPanel2.add(edtRT, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 50, 30));

        edtRW.setEditable(false);
        edtRW.setBackground(new java.awt.Color(255, 255, 255));
        edtRW.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtRW.setBorder(null);
        jPanel2.add(edtRW, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 50, 30));

        edtKeperluan.setColumns(20);
        edtKeperluan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtKeperluan.setRows(5);
        edtKeperluan.setBorder(null);
        jScrollPane1.setViewportView(edtKeperluan);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 910, 230));

        edtTanggal.setDateFormatString("d MMM  yyyy");
        edtTanggal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(edtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 210, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\form pengajuan surat.png")); // NOI18N
        jLabel4.setFocusable(false);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnAjukan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjukanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnAjukanLayout = new javax.swing.GroupLayout(btnAjukan);
        btnAjukan.setLayout(btnAjukanLayout);
        btnAjukanLayout.setHorizontalGroup(
            btnAjukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        btnAjukanLayout.setVerticalGroup(
            btnAjukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(btnAjukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 750, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void edtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNamaActionPerformed

    private void btnAjukanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjukanMouseClicked

        //melakukan dialog konfirmasi
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah data surat sudah benar ?");

        switch (confirm) {
            case JOptionPane.YES_OPTION:
                //pemanggilan method
                insertDataDashboard();
                insertJenisSurat();
                insertSuratPengantar();
                //menampilkan frame DashboardUser
                new DashboardUser(dataUser.getPassword()).setVisible(true);
                this.setVisible(false);
                JOptionPane.showMessageDialog(this, "Surat Pengantar berhasil diajukan");
            case JOptionPane.NO_OPTION:
                break;
        }
    }//GEN-LAST:event_btnAjukanMouseClicked

    private void btnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseClicked
        new ProfileUser(dataUser.getPassword()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnProfileMouseClicked

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        new DashboardUser(dataUser.getPassword()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        JOptionPane jOptionPane = new JOptionPane();
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin LOG OUT?");

        switch (confirm) {
            case JOptionPane.YES_OPTION:
                new Login().setVisible(true);
                this.setVisible(false);
                JOptionPane.showMessageDialog(this, "Anda telah Log out");
            case JOptionPane.NO_OPTION:
                break;
        }
    }//GEN-LAST:event_btnLogOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengajuanSurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengajuanSurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengajuanSurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengajuanSurat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PengajuanSurat(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAjukan;
    private javax.swing.JPanel btnClose;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JPanel btnMinimize;
    private javax.swing.JLabel btnProfile;
    private javax.swing.JComboBox<String> cbSuratPengantar;
    private javax.swing.JTextField edtAlamat;
    private javax.swing.JTextArea edtKeperluan;
    private javax.swing.JTextField edtNIK;
    private javax.swing.JTextField edtNama;
    private javax.swing.JTextField edtRT;
    private javax.swing.JTextField edtRW;
    private com.toedter.calendar.JDateChooser edtTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
