package ui.user;

import model.User;
import database.Koneksi;
import database.SmartDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ui.Login;

public class ProfileUser extends javax.swing.JFrame {

    
    private Connection conn;
    private PreparedStatement pst;
    private ResultSet rst;
    private SmartDatabase database;
    private User data = new User();

    /**
     * Creates new form Profile
     */
    public ProfileUser(String input) {
        initComponents();
        data.setPassword(input);
        try {
            //melakukan koneksi ke database
            database = new SmartDatabase();
            conn = Koneksi.koneksi();
            //menyiapkan statement & memeanggil method queryProfile()
            pst = conn.prepareStatement(database.queryProfile());
            pst.setString(1, input);
            rst = pst.executeQuery(); //eksekusi query

            if (rst.next()) {
                //mengambil data sesuai nama kolomnya
                edtNama.setText(rst.getString("nama"));
                edtNIK.setText(rst.getString("nik"));
                edtAlamat.setText(rst.getString("alamat"));
                edtRT.setText(rst.getString("rt"));
                edtRW.setText(rst.getString("rw"));
                edtNoKK.setText(rst.getString("No_KK"));
                edtTempatLahir.setText(rst.getString("tempat_lahir"));
                edtTglLahir.setText(rst.getString("Tanggal_lahir"));
                edtGender.setText(rst.getString("Jenis_Kelamin"));
                edtAgama.setText(rst.getString("Agama"));
                edtPendidikan.setText(rst.getString("Pendidikan"));
                edtPekerjaan.setText(rst.getString("Pekerjaan"));
                edtStatusKawin.setText(rst.getString("Status_kawin"));
                edtKodeDomisili.setText(rst.getString("Kd_domisili"));
                edtWargaNegara.setText(rst.getString("Warga_negara"));
                edtProvinsi.setText(rst.getString("provinsi"));
                edtKota.setText(rst.getString("kota"));
                edtKecamatan.setText(rst.getString("kecamatan"));
                edtKelurahan.setText(rst.getString("kelurahan"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        edtNama = new javax.swing.JTextField();
        edtRT = new javax.swing.JTextField();
        edtRW = new javax.swing.JTextField();
        edtNIK = new javax.swing.JTextField();
        edtNoKK = new javax.swing.JTextField();
        edtTempatLahir = new javax.swing.JTextField();
        edtTglLahir = new javax.swing.JTextField();
        edtGender = new javax.swing.JTextField();
        edtAgama = new javax.swing.JTextField();
        edtPendidikan = new javax.swing.JTextField();
        edtPekerjaan = new javax.swing.JTextField();
        edtStatusKawin = new javax.swing.JTextField();
        edtKodeDomisili = new javax.swing.JTextField();
        edtWargaNegara = new javax.swing.JTextField();
        edtProvinsi = new javax.swing.JTextField();
        edtKota = new javax.swing.JTextField();
        edtKecamatan = new javax.swing.JTextField();
        edtKelurahan = new javax.swing.JTextField();
        edtAlamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JLabel();
        btnPengajuanSurat = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\icon close.png")); // NOI18N

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCloseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 40, 40));

        btnMinimize.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\icon minimize.png")); // NOI18N

        javax.swing.GroupLayout btnMinimizeLayout = new javax.swing.GroupLayout(btnMinimize);
        btnMinimize.setLayout(btnMinimizeLayout);
        btnMinimizeLayout.setHorizontalGroup(
            btnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMinimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );
        btnMinimizeLayout.setVerticalGroup(
            btnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMinimizeLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 40, 40));

        edtNama.setEditable(false);
        edtNama.setBackground(new java.awt.Color(255, 255, 255));
        edtNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtNama.setBorder(null);
        jPanel1.add(edtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 290, 30));

        edtRT.setEditable(false);
        edtRT.setBackground(new java.awt.Color(255, 255, 255));
        edtRT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtRT.setBorder(null);
        jPanel1.add(edtRT, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 40, 30));

        edtRW.setEditable(false);
        edtRW.setBackground(new java.awt.Color(255, 255, 255));
        edtRW.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtRW.setBorder(null);
        jPanel1.add(edtRW, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 40, 30));

        edtNIK.setEditable(false);
        edtNIK.setBackground(new java.awt.Color(255, 255, 255));
        edtNIK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtNIK.setBorder(null);
        jPanel1.add(edtNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 440, 30));

        edtNoKK.setEditable(false);
        edtNoKK.setBackground(new java.awt.Color(255, 255, 255));
        edtNoKK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtNoKK.setBorder(null);
        jPanel1.add(edtNoKK, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 440, 30));

        edtTempatLahir.setEditable(false);
        edtTempatLahir.setBackground(new java.awt.Color(255, 255, 255));
        edtTempatLahir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtTempatLahir.setBorder(null);
        jPanel1.add(edtTempatLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 200, 30));

        edtTglLahir.setEditable(false);
        edtTglLahir.setBackground(new java.awt.Color(255, 255, 255));
        edtTglLahir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtTglLahir.setBorder(null);
        jPanel1.add(edtTglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 210, 30));

        edtGender.setEditable(false);
        edtGender.setBackground(new java.awt.Color(255, 255, 255));
        edtGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtGender.setBorder(null);
        jPanel1.add(edtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 200, 30));

        edtAgama.setEditable(false);
        edtAgama.setBackground(new java.awt.Color(255, 255, 255));
        edtAgama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtAgama.setBorder(null);
        jPanel1.add(edtAgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 200, 30));

        edtPendidikan.setEditable(false);
        edtPendidikan.setBackground(new java.awt.Color(255, 255, 255));
        edtPendidikan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtPendidikan.setBorder(null);
        jPanel1.add(edtPendidikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 440, 30));

        edtPekerjaan.setEditable(false);
        edtPekerjaan.setBackground(new java.awt.Color(255, 255, 255));
        edtPekerjaan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtPekerjaan.setBorder(null);
        jPanel1.add(edtPekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 440, 30));

        edtStatusKawin.setEditable(false);
        edtStatusKawin.setBackground(new java.awt.Color(255, 255, 255));
        edtStatusKawin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtStatusKawin.setBorder(null);
        jPanel1.add(edtStatusKawin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 200, 30));

        edtKodeDomisili.setEditable(false);
        edtKodeDomisili.setBackground(new java.awt.Color(255, 255, 255));
        edtKodeDomisili.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtKodeDomisili.setBorder(null);
        jPanel1.add(edtKodeDomisili, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 650, 210, 30));

        edtWargaNegara.setEditable(false);
        edtWargaNegara.setBackground(new java.awt.Color(255, 255, 255));
        edtWargaNegara.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtWargaNegara.setBorder(null);
        jPanel1.add(edtWargaNegara, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 430, 30));

        edtProvinsi.setEditable(false);
        edtProvinsi.setBackground(new java.awt.Color(255, 255, 255));
        edtProvinsi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtProvinsi.setBorder(null);
        jPanel1.add(edtProvinsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 430, 30));

        edtKota.setEditable(false);
        edtKota.setBackground(new java.awt.Color(255, 255, 255));
        edtKota.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtKota.setBorder(null);
        jPanel1.add(edtKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 430, 30));

        edtKecamatan.setEditable(false);
        edtKecamatan.setBackground(new java.awt.Color(255, 255, 255));
        edtKecamatan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtKecamatan.setBorder(null);
        jPanel1.add(edtKecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 430, 40));

        edtKelurahan.setEditable(false);
        edtKelurahan.setBackground(new java.awt.Color(255, 255, 255));
        edtKelurahan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtKelurahan.setBorder(null);
        jPanel1.add(edtKelurahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 430, 30));

        edtAlamat.setEditable(false);
        edtAlamat.setBackground(new java.awt.Color(255, 255, 255));
        edtAlamat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtAlamat.setBorder(null);
        jPanel1.add(edtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 430, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\form profile.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDashboard.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\btnDashboard.png")); // NOI18N
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });
        jPanel2.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        btnPengajuanSurat.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\btnPengajuanSurat_white.png")); // NOI18N
        btnPengajuanSurat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPengajuanSuratMouseClicked(evt);
            }
        });
        jPanel2.add(btnPengajuanSurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\btnProfile.png")); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        btnLogOut.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\log out.png")); // NOI18N
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
        });
        jPanel2.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\frame.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        new DashboardUser(data.getPassword()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnPengajuanSuratMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPengajuanSuratMouseClicked
        new PengajuanSurat(data.getPassword()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPengajuanSuratMouseClicked

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        JOptionPane jOptionPane = new JOptionPane();
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin LOG OUT?");

        switch (confirm) {
            case JOptionPane.YES_OPTION:
                new Login().setVisible(true);
                this.setVisible(false);
                JOptionPane.showMessageDialog(this, "Anda telah Log out");
            case JOptionPane.NO_OPTION:
                break;
        }
    }//GEN-LAST:event_btnLogOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ProfileUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnClose;
    private javax.swing.JLabel btnDashboard;
    private javax.swing.JLabel btnLogOut;
    private javax.swing.JPanel btnMinimize;
    private javax.swing.JLabel btnPengajuanSurat;
    private javax.swing.JTextField edtAgama;
    private javax.swing.JTextField edtAlamat;
    private javax.swing.JTextField edtGender;
    private javax.swing.JTextField edtKecamatan;
    private javax.swing.JTextField edtKelurahan;
    private javax.swing.JTextField edtKodeDomisili;
    private javax.swing.JTextField edtKota;
    private javax.swing.JTextField edtNIK;
    private javax.swing.JTextField edtNama;
    private javax.swing.JTextField edtNoKK;
    private javax.swing.JTextField edtPekerjaan;
    private javax.swing.JTextField edtPendidikan;
    private javax.swing.JTextField edtProvinsi;
    private javax.swing.JTextField edtRT;
    private javax.swing.JTextField edtRW;
    private javax.swing.JTextField edtStatusKawin;
    private javax.swing.JTextField edtTempatLahir;
    private javax.swing.JTextField edtTglLahir;
    private javax.swing.JTextField edtWargaNegara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
