package ui.admin;

import model.User;
import model.surat.SuratPengantar;
import database.Koneksi;
import database.SmartDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.print.attribute.standard.Finishings;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Konfirmasi extends javax.swing.JFrame {

    private SmartDatabase database = new SmartDatabase();
    private SuratPengantar dataSurat = new SuratPengantar();
    private User dataUser = new User();
    private Connection conn;
    private PreparedStatement pst;

    public Konfirmasi( String nama,String nik,String keperluan, 
                String status, String linkSurat) {
        initComponents(); 
        dataUser.setNik(nik);
        dataSurat.setKeperluan(keperluan);
        
        edtNama.setText(nama);
        edtStatus.setText(status);
        edtLinkSurat.setText(linkSurat);        
    }

    private void updateLink() {
        dataSurat.setLinkSurat(edtLinkSurat.getText().toString().trim());

        try {
            conn = Koneksi.koneksi();
            pst = conn.prepareStatement(database.updateLink(dataSurat.getLinkSurat()));
            pst.setString(1, dataUser.getNik());
            pst.setString(2, dataSurat.getKeperluan());
            pst.execute();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void updateStatus() {
        dataSurat.setStatus(edtStatus.getText().toString().trim());

        try {
            conn = Koneksi.koneksi();
            pst = conn.prepareStatement(database.updateStatus(dataSurat.getStatus()));
            pst.setString(1, dataUser.getNik());   
            pst.setString(2, dataSurat.getKeperluan());
            pst.execute();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        edtStatus = new javax.swing.JTextField();
        edtLinkSurat = new javax.swing.JTextField();
        btnClose = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        edtNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnKirim = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtStatus.setBorder(null);
        edtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtStatusActionPerformed(evt);
            }
        });
        jPanel1.add(edtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 250, 30));

        edtLinkSurat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtLinkSurat.setBorder(null);
        jPanel1.add(edtLinkSurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 250, 30));

        btnClose.setBackground(new java.awt.Color(255, 255, 255));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\icon close.png")); // NOI18N

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCloseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 40, 40));

        btnMinimize.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\icon minimize.png")); // NOI18N

        javax.swing.GroupLayout btnMinimizeLayout = new javax.swing.GroupLayout(btnMinimize);
        btnMinimize.setLayout(btnMinimizeLayout);
        btnMinimizeLayout.setHorizontalGroup(
            btnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMinimizeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );
        btnMinimizeLayout.setVerticalGroup(
            btnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMinimizeLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 40, 40));

        edtNama.setEditable(false);
        edtNama.setBackground(new java.awt.Color(255, 255, 255));
        edtNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        edtNama.setBorder(null);
        edtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNamaActionPerformed(evt);
            }
        });
        jPanel1.add(edtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 400, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\konfirmasi.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnKirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKirimMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnKirimLayout = new javax.swing.GroupLayout(btnKirim);
        btnKirim.setLayout(btnKirimLayout);
        btnKirimLayout.setHorizontalGroup(
            btnKirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        btnKirimLayout.setVerticalGroup(
            btnKirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(btnKirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtStatusActionPerformed

    private void edtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNamaActionPerformed

    private void btnKirimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseClicked
        if (edtStatus.getText().toString().trim().equals("") 
                    || edtLinkSurat.getText().toString().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Ada kolom yang harus diisi");
        } else {
            updateStatus();
            updateLink();
            this.setVisible(false);
            JOptionPane.showMessageDialog(this, "Berkas telah dikirim");
        }
    }//GEN-LAST:event_btnKirimMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Konfirmasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnKirim;
    private javax.swing.JPanel btnMinimize;
    private javax.swing.JTextField edtLinkSurat;
    private javax.swing.JTextField edtNama;
    private javax.swing.JTextField edtStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
