package ui;

import model.User;
import database.Koneksi;
import database.SmartDatabase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ui.admin.DashboardAdmin;
import ui.user.DashboardUser;

public class Login extends javax.swing.JFrame {
    //instance variable
    private Connection conn;
    private PreparedStatement pst;
    private ResultSet rst;
    private SmartDatabase database;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        edtUsername = new javax.swing.JTextField();
        edtPassword = new javax.swing.JPasswordField();
        cbOption = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        minimize = new javax.swing.JPanel();
        btnRegister = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(426, 537));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtUsername.setBackground(new java.awt.Color(92, 92, 92));
        edtUsername.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edtUsername.setForeground(new java.awt.Color(255, 255, 255));
        edtUsername.setBorder(null);
        edtUsername.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        edtUsername.setSelectionColor(new java.awt.Color(255, 255, 255));
        edtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(edtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 410, 50));

        edtPassword.setBackground(new java.awt.Color(87, 87, 87));
        edtPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edtPassword.setForeground(new java.awt.Color(255, 255, 255));
        edtPassword.setBorder(null);
        getContentPane().add(edtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 410, 50));

        cbOption.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USER", "ADMIN" }));
        cbOption.setBorder(null);
        cbOption.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(cbOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 430, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\Login.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        btnLoginLayout.setVerticalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 160, 40));

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout closeLayout = new javax.swing.GroupLayout(close);
        close.setLayout(closeLayout);
        closeLayout.setHorizontalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        closeLayout.setVerticalGroup(
            closeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 30, 40));

        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout minimizeLayout = new javax.swing.GroupLayout(minimize);
        minimize.setLayout(minimizeLayout);
        minimizeLayout.setHorizontalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        minimizeLayout.setVerticalGroup(
            minimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 30, 30));

        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnRegisterLayout = new javax.swing.GroupLayout(btnRegister);
        btnRegister.setLayout(btnRegisterLayout);
        btnRegisterLayout.setHorizontalGroup(
            btnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        btnRegisterLayout.setVerticalGroup(
            btnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 190, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void edtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtUsernameActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        //Membuat objek data yang mereferensi ke objek User();
        User data = new User();
        
        //melakukan setter dengan mengambil inputan dari JFrame Form
        data.setUsername(edtUsername.getText().toString().trim());
        data.setPassword(edtPassword.getText().toString().trim());
        data.setOption(cbOption.getSelectedItem().toString().trim());

        //jika terdapat kolom inputan yang kosong
        if (data.getUsername().equals("") || data.getPassword().equals("")) {
            //maka akan diberikan pesan dialog 
            JOptionPane.showMessageDialog(rootPane, "Kolom harus dilengkapi");
        } else {
            try {
                //inisialisasi variable yang mereference ke objek SmartDatabase()
                database = new SmartDatabase();
                conn = Koneksi.koneksi();
                //menyiapkan statement dengan memeanggil method queryAdmin()
                pst = conn.prepareStatement(database.queryAdmin());
                //memasukkan data inputan username & password ke dalam statement
                pst.setString(1, data.getUsername());
                pst.setString(2, data.getPassword());
                //mengeksekusi query statement
                rst = pst.executeQuery();

                //pengondisian
                if (rst.next()) {
                    //mengambil data pada kolom "option"
                    String op = rst.getString("option");
                    
                    //jika yang melakukan login adalah admin
                    if (data.getOption().equals("ADMIN") && op.equals("Admin")) {
                        //maka akan menampilkan Frame DashboardAdmin
                        DashboardAdmin da = new DashboardAdmin(data.getPassword());
                        da.setVisible(true);
                        
                        this.setVisible(false);
                        JOptionPane.showMessageDialog(rootPane, "Kamu Berhasil Masuk");
                    
                    //jika yang melakukan login adalah user
                    } else if (data.getOption().equals("USER") && op.equals("USER")) {
                        //maka akan menampilkan Frame DashboardUser
                        DashboardUser da = new DashboardUser(data.getPassword());
                        da.setVisible(true);
                        this.setVisible(false);
                        JOptionPane.showMessageDialog(rootPane, "Kamu Berhasil Masuk");
                    } 
                    
                    
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        new Catatan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegisterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    Thread.sleep(4000);
                    new Login().setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnLogin;
    private javax.swing.JPanel btnRegister;
    private javax.swing.JComboBox<String> cbOption;
    private javax.swing.JPanel close;
    private javax.swing.JPasswordField edtPassword;
    private javax.swing.JTextField edtUsername;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel minimize;
    // End of variables declaration//GEN-END:variables
}
