package ui;

import model.Domisili;
import model.User;
import database.Koneksi;
import database.SmartDatabase;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ui.admin.DashboardAdmin;

public class Register extends javax.swing.JFrame {

    private Connection conn;
    private PreparedStatement pst;
    private ResultSet rst;
    private User data;
    private SmartDatabase database;

    public Register(String input) {
        initComponents();
        edtKodeDomisili.setText(input);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        edtUsername = new javax.swing.JTextField();
        edtNama = new javax.swing.JTextField();
        edtNIK = new javax.swing.JTextField();
        edtNoKK = new javax.swing.JTextField();
        edtTempatLahir = new javax.swing.JTextField();
        edtWargaNegara = new javax.swing.JTextField();
        edtKodeDomisili = new javax.swing.JTextField();
        edtOption = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox<>();
        cbAgama = new javax.swing.JComboBox<>();
        cbStatusNikah = new javax.swing.JComboBox<>();
        edtPassword = new javax.swing.JPasswordField();
        edtPendidikan = new javax.swing.JTextField();
        edtPekerjaan = new javax.swing.JTextField();
        edtTanggalLahir = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        btnNext = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setBackground(new java.awt.Color(87, 87, 87));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\close_white.png")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCloseLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, 40, 40));

        btnMinimize.setBackground(new java.awt.Color(87, 87, 87));
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\minimize_white.png")); // NOI18N

        javax.swing.GroupLayout btnMinimizeLayout = new javax.swing.GroupLayout(btnMinimize);
        btnMinimize.setLayout(btnMinimizeLayout);
        btnMinimizeLayout.setHorizontalGroup(
            btnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMinimizeLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnMinimizeLayout.setVerticalGroup(
            btnMinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMinimizeLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, 40, 40));

        edtUsername.setBackground(new java.awt.Color(87, 87, 87));
        edtUsername.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edtUsername.setForeground(new java.awt.Color(255, 255, 255));
        edtUsername.setBorder(null);
        edtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(edtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 340, 50));

        edtNama.setBackground(new java.awt.Color(87, 87, 87));
        edtNama.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edtNama.setForeground(new java.awt.Color(255, 255, 255));
        edtNama.setBorder(null);
        getContentPane().add(edtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 560, 50));

        edtNIK.setBackground(new java.awt.Color(87, 87, 87));
        edtNIK.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edtNIK.setForeground(new java.awt.Color(255, 255, 255));
        edtNIK.setBorder(null);
        getContentPane().add(edtNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 560, 50));

        edtNoKK.setBackground(new java.awt.Color(87, 87, 87));
        edtNoKK.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edtNoKK.setForeground(new java.awt.Color(255, 255, 255));
        edtNoKK.setBorder(null);
        getContentPane().add(edtNoKK, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 560, 50));

        edtTempatLahir.setBackground(new java.awt.Color(87, 87, 87));
        edtTempatLahir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edtTempatLahir.setForeground(new java.awt.Color(255, 255, 255));
        edtTempatLahir.setBorder(null);
        getContentPane().add(edtTempatLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 260, 50));

        edtWargaNegara.setBackground(new java.awt.Color(87, 87, 87));
        edtWargaNegara.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edtWargaNegara.setForeground(new java.awt.Color(255, 255, 255));
        edtWargaNegara.setBorder(null);
        getContentPane().add(edtWargaNegara, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 540, 50));

        edtKodeDomisili.setEditable(false);
        edtKodeDomisili.setBackground(new java.awt.Color(87, 87, 87));
        edtKodeDomisili.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edtKodeDomisili.setForeground(new java.awt.Color(255, 255, 255));
        edtKodeDomisili.setBorder(null);
        edtKodeDomisili.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtKodeDomisiliActionPerformed(evt);
            }
        });
        getContentPane().add(edtKodeDomisili, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 470, 260, 50));

        edtOption.setEditable(false);
        edtOption.setBackground(new java.awt.Color(87, 87, 87));
        edtOption.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edtOption.setForeground(new java.awt.Color(255, 255, 255));
        edtOption.setText("USER");
        edtOption.setBorder(null);
        getContentPane().add(edtOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 60, 50));

        cbGender.setEditable(true);
        cbGender.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        cbGender.setBorder(null);
        getContentPane().add(cbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 250, 70));

        cbAgama.setEditable(true);
        cbAgama.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Konghuchu", "Budha", "Hindu" }));
        cbAgama.setBorder(null);
        getContentPane().add(cbAgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 280, 70));

        cbStatusNikah.setEditable(true);
        cbStatusNikah.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbStatusNikah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Kawin", "Sudah Kawin", " " }));
        getContentPane().add(cbStatusNikah, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 250, 70));

        edtPassword.setBackground(new java.awt.Color(87, 87, 87));
        edtPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edtPassword.setForeground(new java.awt.Color(255, 255, 255));
        edtPassword.setBorder(null);
        getContentPane().add(edtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 560, 50));

        edtPendidikan.setBackground(new java.awt.Color(87, 87, 87));
        edtPendidikan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edtPendidikan.setForeground(new java.awt.Color(255, 255, 255));
        edtPendidikan.setBorder(null);
        getContentPane().add(edtPendidikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 540, 50));

        edtPekerjaan.setBackground(new java.awt.Color(87, 87, 87));
        edtPekerjaan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        edtPekerjaan.setForeground(new java.awt.Color(255, 255, 255));
        edtPekerjaan.setBorder(null);
        getContentPane().add(edtPekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 540, 40));

        edtTanggalLahir.setBackground(new java.awt.Color(255, 255, 255));
        edtTanggalLahir.setDateFormatString("yyyy-MM-dd");
        edtTanggalLahir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(edtTanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 670, 250, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Pictures\\Figma project\\SMART RT RW\\Registrasi.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnNextLayout = new javax.swing.GroupLayout(btnNext);
        btnNext.setLayout(btnNextLayout);
        btnNextLayout.setHorizontalGroup(
            btnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        btnNextLayout.setVerticalGroup(
            btnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 660, 540, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        /*inisialisasi objek supaya format tanggal yang di inputkan 
        menjadi sesuai dengan format tanggal di sql*/
        java.sql.Date date = new Date(edtTanggalLahir.getDate().getTime());
        String username = edtUsername.getText().toString().trim();
        String password = edtPassword.getText().toString().trim();
        String option = edtOption.getText().toString();
        String nik = edtNIK.getText().toString();
        String nama = edtNama.getText().toString().trim();
        String noKK = edtNoKK.getText().toString();
        String tempatLahir = edtTempatLahir.getText().toString().trim();
        String tanggaLahir = date.toString();
        String jenisKelamin = cbGender.getSelectedItem().toString();
        String agama = cbAgama.getSelectedItem().toString();
        String pendidikan = edtPendidikan.getText().toString().trim();
        String pekerjaan = edtPekerjaan.getText().toString().trim();
        String statusNikah = cbStatusNikah.getSelectedItem().toString();
        String kodePos = edtKodeDomisili.getText().toString().trim();
        String wargaNegara = edtWargaNegara.getText().toString().trim();

        data = new User(nik, nama, noKK, tempatLahir, tanggaLahir,
                    jenisKelamin, agama, kodePos, pekerjaan, pendidikan,
                    statusNikah, wargaNegara, username, password, option);

        //Jika ada kolom yang kosong
        if (username.equals("") || password.equals("")
                    || nik.equals("") || nama.equals("")
                    || noKK.equals("") || tempatLahir.equals("")
                    || tanggaLahir.equals("") || pendidikan.equals("")
                    || pekerjaan.equals("") || kodePos.equals("")
                    || wargaNegara.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Kolom harus dilengkapi");
        } else { //jika tidak
            try {
                database = new SmartDatabase();
                conn = Koneksi.koneksi();
                //menyiapkan statement & memeanggil method insertDataWarga(data)
                pst = conn.prepareStatement(database.insertDataWarga(data));

                int confirm = JOptionPane.showConfirmDialog(this, "Apakah data registrasi telah sesuai?");

                switch (confirm) {
                    case JOptionPane.YES_OPTION:
                        pst.execute(); //eksekusi query
                        new Login().setVisible(true);
                        this.setVisible(false);
                        JOptionPane.showMessageDialog(rootPane, "Data berhasil di inputkan");
                    case JOptionPane.NO_OPTION:
                        break;
                }
                

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnNextMouseClicked

    private void edtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtUsernameActionPerformed

    private void edtKodeDomisiliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtKodeDomisiliActionPerformed

    }//GEN-LAST:event_edtKodeDomisiliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register(null).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnClose;
    private javax.swing.JPanel btnMinimize;
    private javax.swing.JPanel btnNext;
    private javax.swing.JComboBox<String> cbAgama;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbStatusNikah;
    private javax.swing.JTextField edtKodeDomisili;
    private javax.swing.JTextField edtNIK;
    private javax.swing.JTextField edtNama;
    private javax.swing.JTextField edtNoKK;
    private javax.swing.JTextField edtOption;
    private javax.swing.JPasswordField edtPassword;
    private javax.swing.JTextField edtPekerjaan;
    private javax.swing.JTextField edtPendidikan;
    private com.toedter.calendar.JDateChooser edtTanggalLahir;
    private javax.swing.JTextField edtTempatLahir;
    private javax.swing.JTextField edtUsername;
    private javax.swing.JTextField edtWargaNegara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
